version: '3.7'

services:
  eyegate:
    image: eyegate:1.0
    build: .
    command: python EyeGate.py
    network_mode: host
    restart: always
    env_file:
      - ./.env

  dresscoder:
    image: dresscoder:1.0
    build: .
    command: python DressCoder.py
    network_mode: host
    restart: always
    env_file:
      - ./.env