version: '3.7'
services:
  web:
    build: .
    command: python EyeGate.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8080:8080
      - 80:80
    restart: always
    env_file:
      - ./.env